version: '3.7'

services:
  backend:
    build:
      context: ./back-end
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_URL=${POSTGRES_URL}
    networks:
      - app-network
    depends_on:
      - database
    container_name: back-end-container


  database:
    build:
      context: ./db
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - my-vol:/var/lib/postgresql/data
    container_name: db-container

  http:
    build:
      context: ./http
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - backend
    container_name: front-end-container

networks:
  app-network:
    driver: bridge

volumes:
  my-vol:
