spring:
  datasource:
    url: jdbc:postgresql://db-container:5432/db
    username: usr
    password: pwd
    driver-class-name: org.postgresql.Driver

  jpa:
    generate-ddl: false
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true

management:
  server:
    add-application-context-header: false
  endpoints:
    web:
      exposure:
        include: health,info,env,metrics,beans,configprops
